name: Docker Image Build

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u whoemi --password-stdin

      - name: Build Docker Image
        run: docker build -t whomei/ubuntu:latest .

      - name: Push Docker Image
        run: docker push whomei/ubuntu:latest

      - name: Logout from DockerHub
        run: docker logout
